### ISSUE TITLE
Create HMR module

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box-aurelia-seed#2]
subj when ready =)

**Comment by nchanged** [comment]
https://github.com/fuse-box/fuse-box-aurelia-loader/issues/8

**Comment by arjendeblok** [comment]
Got it working now in a test setup for views, but not for viewmodels yet. 
Working on it.

**Comment by vegarringdal** [comment]
@arjendeblok 
How is the HMR plugin going, last time I tried it it worked very well and just needed making it into a plugin so it only added code if in development mode or something

**Comment by arjendeblok** [comment]
@vegarringdal I did not change the HMR plugin since last time you tried.
Should I make a PR to include the HMR plugin in the Aurelia loader package?

**Comment by vegarringdal** [comment]
I think having the plugin as own repo is best, because you would only want to include it and the aurelia-hotreload module with use of devServer.

Not sure how to do this best.
If you are able to make a own repo for now with such a plugin we can add for now then that would be great.
I could learn from it on how to make plugins 👍 so much more fun when others have done 99% of the job 😄

**Comment by vegarringdal** [comment]
closing, since old seed is replaced and updated to fusebox 2.0
